parameters:
  - name: 'environments'
    type: object
    default:
        - environment: lab
          region: ['em23']
          terraformstg: containername
          terraformrg: containerrg 
          azuresub: 'sub-name'
          
        - environment: dev
          dependsOn: 'lab_em23_apply'
          region: ['em22']
          terraformstg: containername
          terraformrg: containerrg 
          azuresub: 'sub-name'
          
        - environment: qa
          dependsOn: 'dev_em22_apply'
          region: ['em22']
          terraformstg: containername
          terraformrg: containerrg 
          azuresub: 'sub-name'
       
        - environment: iat
          dependsOn: 'qa_em22_apply'
          region: ['em22','na20']
          terraformstg: containername
          terraformrg: containerrg 
          azuresub: 'sub-name'

        - environment: prod
          dependsOn: 'iat_em22_apply'
          region: ['em22','na20']
          terraformstg: containername
          terraformrg: containerrg 
          azuresub: 'sub-name' 
  - name: workingdirectory
    type: string
  - name: applicationresourcegroupidentifier
    type: string
  - name: backendcontainerprefix
    type: string
  - name: isaddvargroupsuffix
    type: boolean
    default: false

trigger:
  branches:
    include:
    - main
  paths:
    include: 
      - 'examples/*'

resources:
  repositories:
    - repository: RIC.DevOps
      type: git
      name: RIC.DevOps
pool:
  vmImage: 'windows-latest'

variables:
  - group: example-var-group

extends:
  template: /builds/terraform-main.yml@RIC.DevOps
  parameters:
    environments: ${{parameters.environments}}
    workingdirectory: ${{parameters.workingdirectory}}
    applicationresourcegroupidentifier: ${{parameters.applicationresourcegroupidentifier}}
    backendcontainerprefix: ${{parameters.backendcontainerprefix}}
    isaddvargroupsuffix: ${{parameters.isaddvargroupsuffix}}
